=== CyberSecAI/cve_info/cve_schema_1.0.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "CVE Entry Schema",
    "description": "Schema for CVE entries with technical impacts and keyphrases",
    "required": [
        "cveId",
        "version",
        "timestamp",
        "description",
        "keyphrases",
        "mitreTechnicalImpacts"
    ],
    "properties": {
        "cveId": {
            "type": "string",
            "pattern": "^CVE-\\d{4}-\\d+$",
            "description": "The CVE identifier in format CVE-YYYY-NNNN"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$",
            "description": "Semantic version number"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "ISO 8601 timestamp of when the entry was created"
        },
        "description": {
            "type": "string",
            "minLength": 1,
            "description": "Full description of the vulnerability"
        },
        "keyphrases": {
            "type": "object",
            "description": "Key phrases extracted from the vulnerability description",
            "required": [
                "rootcause",
                "weakness",
                "impact",
                "vector",
                "attacker",
                "product",
                "version",
                "component"
            ],
            "properties": {
                "rootcause": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The root cause(s) of the vulnerability"
                },
                "weakness": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The weakness(es) or vulnerability type(s)"
                },
                "impact": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The impact(s) of exploiting the vulnerability"
                },
                "vector": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The attack vector(s) or method(s) of exploitation"
                },
                "attacker": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The type(s) of attacker who can exploit the vulnerability"
                },
                "product": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product name(s)"
                },
                "version": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product version(s)"
                },
                "component": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The specific component(s) affected"
                }
            },
            "additionalProperties": false
        },
        "mitreTechnicalImpacts": {
            "type": "array",
            "description": "List of MITRE technical impact classifications",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        }
    },
    "additionalProperties": false
}

=== CyberSecAI/cve_info/2022/21xxx/CVE-2022-21947.json
{
    "cveId": "CVE-2022-21947",
    "version": "1.0.0",
    "timestamp": "2024-11-03T18:37:50.907685+00:00",
    "description": "A Exposure of Resource to Wrong Sphere vulnerability in Rancher Desktop of SUSE allows attackers in the local network to connect to the Dashboard API (steve) to carry out arbitrary actions. This issue affects SUSE Rancher Desktop versions prior to V.",
    "keyphrases": {
        "rootcause": "Exposure of Resource to Wrong Sphere",
        "weakness": "",
        "impact": "carry out arbitrary actions",
        "vector": "",
        "attacker": "attackers in the local network",
        "product": "SUSE Rancher Desktop",
        "version": "prior to V",
        "component": "Dashboard API"
    },
    "mitreTechnicalImpacts": [
        "Execute unauthorized code or commands",
        "Modify data",
        "Read data"
    ]
}

=== CyberSecAI/cve_info/2006/4xxx/CVE-2006-4966.json
{
  "cveId": "CVE-2006-4966",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "PHP remote file inclusion vulnerability in inc/ifunctions.php in chumpsoft phpQuestionnaire (phpQ) 3.12 allows remote attackers to execute arbitrary PHP code via a URL in the GLOBALS[phpQRootDir] parameter.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "remote file inclusion",
    "impact": "execute arbitrary PHP code",
    "vector": "URL in GLOBALS[phpQRootDir] parameter",
    "attacker": "remote attackers",
    "product": "chumpsoft phpQuestionnaire (phpQ)",
    "version": "3.12",
    "component": "inc/ifunctions.php"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2012/2xxx/CVE-2012-2800.json
{
  "cveId": "CVE-2012-2800",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "Unspecified vulnerability in the ff_ivi_process_empty_tile function in libavcodec/ivi_common.c in FFmpeg before 0.11, and Libav 0.7.x before 0.7.7 and 0.8.x before 0.8.4, has unknown impact and attack vectors in which the tile size ... mismatches parameters and triggers writing into a too small array.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "write into a too small array",
    "impact": "unknown impact",
    "vector": "tile size mismatches parameters",
    "attacker": "",
    "product": [
      "['FFmpeg'",
      "'Libav']"
    ],
    "version": [
      "['before 0.11'",
      "'0.7.x before 0.7.7'",
      "'0.8.x before 0.8.4']"
    ],
    "component": "ff_ivi_process_empty_tile function in libavcodec/ivi_common.c"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2014/2xxx/CVE-2014-2739.json
{
  "cveId": "CVE-2014-2739",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "The cma_req_handler function in drivers/infiniband/core/cma.c in the Linux kernel 3.14.x through 3.14.1 attempts to resolve an RDMA over Converged Ethernet (aka RoCE) address that is properly resolved within a different module, which allows remote attackers to cause a denial of service (incorrect pointer dereference and system crash) via crafted network traffic.",
  "keyphrases": {
    "rootcause": "incorrect pointer dereference",
    "weakness": "",
    "impact": [
      "denial of service",
      "system crash"
    ],
    "vector": "crafted network traffic",
    "attacker": "remote attackers",
    "product": "Linux kernel",
    "version": "3.14.x through 3.14.1",
    "component": "cma_req_handler function"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2008/5xxx/CVE-2008-5075.json
{
  "cveId": "CVE-2008-5075",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "Multiple SQL injection vulnerabilities in E-Uploader Pro 1.0 (aka Uploader PRO), when magic_quotes_gpc is disabled, allow remote attackers to execute arbitrary SQL commands via the (1) id parameter to (a) img.php, (b) file.php, (c) mail.php, (d) thumb.php, (e) zip.php, and (f) zipit.php, and (2) the view parameter to (g) browser.php.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "SQL injection vulnerabilities",
    "impact": "execute arbitrary SQL commands",
    "vector": "",
    "attacker": "remote attackers",
    "product": "E-Uploader Pro",
    "version": "1",
    "component": [
      "['img.php'",
      "'file.php'",
      "'mail.php'",
      "'thumb.php'",
      "'zip.php'",
      "'zipit.php'",
      "'browser.php']"
    ]
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2022/26xxx/CVE-2022-26763.json
{
  "cveId": "CVE-2022-26763",
  "version": "1.0.0",
  "timestamp": "2024-11-03T18:37:50.907685+00:00",
  "description": "An out-of-bounds access issue was addressed with improved bounds checking. This issue is fixed in tvOS 15.5, iOS 15.5 and iPadOS 15.5, Security Update 2022-004 Catalina, watchOS 8.6, macOS Big Sur 11.6.6, macOS Monterey 12.4. A malicious application may be able to execute arbitrary code with system privileges.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "out-of-bounds access",
    "impact": [
      "arbitrary code execution",
      "execute arbitrary code"
    ],
    "vector": "",
    "attacker": "malicious application",
    "product": [
      "['tvOS'",
      "'iOS'",
      "'iPadOS'",
      "'macOS'",
      "'watchOS']"
    ],
    "version": [
      "['15.5'",
      "'15.5'",
      "'15.5'",
      "'Big Sur 11.6.6'",
      "'Monterey 12.4'",
      "'8.6']"
    ],
    "component": ""
  },
  "mitreTechnicalImpacts": [
    "Execute unauthorized code or commands"
  ]
}

=== CyberSecAI/cve_info/2008/2xxx/CVE-2008-2198.json
{
  "cveId": "CVE-2008-2198",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "PHP remote file inclusion vulnerability in kmitaadmin/kmitat/htmlcode.php in Kmita Tellfriend 2.0 and earlier, when register_globals is enabled, allows remote attackers to execute arbitrary PHP code via a URL in the file parameter.",
  "keyphrases": {
    "rootcause": "PHP remote file inclusion",
    "weakness": "remote file inclusion",
    "impact": "execute arbitrary PHP code",
    "vector": "URL in file parameter",
    "attacker": "remote attackers",
    "product": "Kmita Tellfriend",
    "version": "2.0 and earlier",
    "component": "kmitaadmin/kmitat/htmlcode.php"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2018/13xxx/CVE-2018-13475.json
{
  "cveId": "CVE-2018-13475",
  "version": "1.0.0",
  "timestamp": "2024-12-12T22:08:52.294043+00:00",
  "description": "The mintToken function of a smart contract implementation for VSCToken, an Ethereum token, has an integer overflow that allows the owner of the contract to set the balance of an arbitrary user to any value.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "integer overflow",
    "impact": "set balance of arbitrary user to any value",
    "vector": "",
    "attacker": "owner of contract",
    "product": "VSCToken",
    "version": "",
    "component": "mintToken function"
  },
  "mitreTechnicalImpacts": []
}
