=== CyberSecAI/cve_info/cve_schema_1.0.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "CVE Entry Schema",
    "description": "Schema for CVE entries with technical impacts and keyphrases",
    "required": [
        "cveId",
        "version",
        "timestamp",
        "description",
        "keyphrases",
        "mitreTechnicalImpacts"
    ],
    "properties": {
        "cveId": {
            "type": "string",
            "pattern": "^CVE-\\d{4}-\\d+$",
            "description": "The CVE identifier in format CVE-YYYY-NNNN"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$",
            "description": "Semantic version number"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "ISO 8601 timestamp of when the entry was created"
        },
        "description": {
            "type": "string",
            "minLength": 1,
            "description": "Full description of the vulnerability"
        },
        "keyphrases": {
            "type": "object",
            "description": "Key phrases extracted from the vulnerability description",
            "required": [
                "rootcause",
                "weakness",
                "impact",
                "vector",
                "attacker",
                "product",
                "version",
                "component"
            ],
            "properties": {
                "rootcause": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The root cause(s) of the vulnerability"
                },
                "weakness": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The weakness(es) or vulnerability type(s)"
                },
                "impact": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The impact(s) of exploiting the vulnerability"
                },
                "vector": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The attack vector(s) or method(s) of exploitation"
                },
                "attacker": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The type(s) of attacker who can exploit the vulnerability"
                },
                "product": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product name(s)"
                },
                "version": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product version(s)"
                },
                "component": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The specific component(s) affected"
                }
            },
            "additionalProperties": false
        },
        "mitreTechnicalImpacts": {
            "type": "array",
            "description": "List of MITRE technical impact classifications",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        }
    },
    "additionalProperties": false
}

=== CyberSecAI/cve_info/2017/0xxx/CVE-2017-0601.json
{
  "cveId": "CVE-2017-0601",
  "version": "1.0.0",
  "timestamp": "2024-12-11T16:08:24.783251+00:00",
  "description": "An Elevation of Privilege vulnerability in Bluetooth could potentially enable a local malicious application to accept harmful files shared via bluetooth without user permission. This issue is rated as Moderate due to local bypass of user interaction requirements. Product Android. Versions 7.0, 7.1.1, 7.1.2. Android ID A-35258579.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "bypass of user interaction requirements",
    "impact": [
      "Elevation of Privilege",
      "accept harmful files shared via bluetooth without user permission"
    ],
    "vector": "",
    "attacker": "local malicious application",
    "product": "Android",
    "version": [
      "7.0",
      "7.1.1",
      "7.1.2"
    ],
    "component": "Bluetooth"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2008/4xxx/CVE-2008-4401.json
{
  "cveId": "CVE-2008-4401",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "ActionScript in Adobe Flash Player 9.0.124.0 and earlier does not require user interaction in conjunction with (1) the FileReference.browse operation in the FileReference upload API or (2) the FileReference.download operation in the FileReference download API, which allows remote attackers to create a browse dialog box, and possibly have unspecified other impact, via an SWF file.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "",
    "impact": [
      "create browse dialog box",
      "possibly have unspecified other impact"
    ],
    "vector": "SWF file",
    "attacker": "remote attackers",
    "product": "Adobe Flash Player",
    "version": "9.0.124.0 and earlier",
    "component": [
      "ActionScript",
      "FileReference upload/download API"
    ]
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2011/5xxx/CVE-2011-5230.json
{
  "cveId": "CVE-2011-5230",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "Multiple SQL injection vulnerabilities in the selectUserIdByLoginPass function in seotoaster_core/application/models/LoginModel.php in Seotoaster 1.9 and earlier allow remote attackers to execute arbitrary SQL commands via the (1) login parameter to sys/login/index or (2) memberLoginName parameter to sys/login/member.",
  "keyphrases": {
    "rootcause": "SQL injection vulnerabilities in the selectUserIdByLoginPass function",
    "weakness": "SQL injection vulnerabilities",
    "impact": "execute arbitrary SQL commands",
    "vector": [
      "login parameter",
      "memberLoginName parameter"
    ],
    "attacker": "remote attackers",
    "product": "Seotoaster",
    "version": "1.9 and earlier",
    "component": "seotoaster_core/application/models/LoginModel.php"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2020/5xxx/CVE-2020-5393.json
{
  "cveId": "CVE-2020-5393",
  "version": "1.0.0",
  "timestamp": "2024-12-12T22:08:52.294043+00:00",
  "description": "In Appspace On-Prem through 7.1.3, an adversary can steal a session token via XSS.",
  "keyphrases": {
    "rootcause": "cross-site scripting",
    "weakness": "XSS",
    "impact": "session token theft",
    "vector": "",
    "attacker": "adversary",
    "product": "Appspace On-Prem",
    "version": "through 7.1.3",
    "component": ""
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2023/6xxx/CVE-2023-6098.json
{
  "cveId": "CVE-2023-6098",
  "version": "1.0.0",
  "timestamp": "2024-12-06T11:32:07.789868+00:00",
  "description": "An XSS vulnerability has been discovered in ICS Business Manager affecting version 7.06.0028.7066. A remote attacker could send a specially crafted string exploiting the obdd_act parameter, allowing the attacker to steal an authenticated users session, and perform actions within the application.",
  "keyphrases": {
    "rootcause": "",
    "weakness": [
      "XSS vulnerability",
      "cross-site scripting"
    ],
    "impact": [
      "['session stealing'",
      "'perform actions']"
    ],
    "vector": "specially crafted string",
    "attacker": "remote attacker",
    "product": "ICS Business Manager",
    "version": "7.06.0028.7066",
    "component": "obdd_act parameter"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2024/20xxx/CVE-2024-20359.json
{
    "cveId": "CVE-2024-20359",
    "version": "1.0.0",
    "timestamp": "2024-11-03T18:37:50.907685+00:00",
    "description": "A vulnerability in a legacy capability that allowed for the preloading of VPN clients and plug-ins and that has been available in Cisco Adaptive Security Appliance (ASA) Software and Cisco Firepower Threat Defense (FTD) Software could allow an authenticated, local attacker to execute arbitrary code with root-level privileges. Administrator-level privileges are required to exploit this vulnerability.\r\n\r This vulnerability is due to improper validation of a file when it is read from system flash memory. An attacker could exploit this vulnerability by copying a crafted file to the disk0: file system of an affected device. A successful exploit could allow the attacker to execute arbitrary code on the affected device after the next reload of the device, which could alter system behavior. Because the injected code could persist across device reboots, Cisco has raised the Security Impact Rating (SIR) of this advisory from Medium to High.",
    "keyphrases": {
        "rootcause": "improper validation of a file when it is read from system flash memory",
        "weakness": "",
        "impact": "execute arbitrary code with root-level privileges",
        "vector": "copying a crafted file to the disk0: file system",
        "attacker": [
            "authenticated",
            "local attacker"
        ],
        "product": [
            "Cisco Adaptive Security Appliance",
            "ASA Software",
            "Cisco Firepower Threat Defense",
            "FTD Software"
        ],
        "version": "",
        "component": ""
    },
    "mitreTechnicalImpacts": [
        "Execute unauthorized code or commands",
        "Gain privileges / assume identity"
    ]
}

=== CyberSecAI/cve_info/2024/51xxx/CVE-2024-51913.json
{
  "cveId": "CVE-2024-51913",
  "version": "1.0.0",
  "timestamp": "2024-12-17T08:36:27.567979+00:00",
  "description": "Improper Neutralization of Input During Web Page Generation (Cross-site Scripting) vulnerability in Mapme Mapme allows Stored XSS.This issue affects Mapme from n/a through 1.3.2.",
  "keyphrases": {
    "rootcause": "Improper Neutralization of Input During Web Page Generation",
    "weakness": [
      "XSS",
      "cross-site scripting"
    ],
    "impact": "Stored XSS",
    "vector": "",
    "attacker": "",
    "product": "Mapme Mapme",
    "version": "n/a through 1.3.2",
    "component": ""
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2002/1xxx/CVE-2002-1069.json
{
  "cveId": "CVE-2002-1069",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "The remote administration capability for the D-Link DI-804 router 4.68 allows remote attackers to bypass authentication and release DHCP addresses or obtain sensitive information via a direct web request to the pages (1) release.htm, (2) Device Status, or (3) Device Information.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "",
    "impact": [
      "bypass authentication",
      "obtain sensitive information"
    ],
    "vector": "direct web request",
    "attacker": "remote attackers",
    "product": "D-Link DI-804 router",
    "version": "4.68",
    "component": "remote administration capability"
  },
  "mitreTechnicalImpacts": []
}
