=== CyberSecAI/cve_info/cve_schema_1.0.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "CVE Entry Schema",
    "description": "Schema for CVE entries with technical impacts and keyphrases",
    "required": [
        "cveId",
        "version",
        "timestamp",
        "description",
        "keyphrases",
        "mitreTechnicalImpacts"
    ],
    "properties": {
        "cveId": {
            "type": "string",
            "pattern": "^CVE-\\d{4}-\\d+$",
            "description": "The CVE identifier in format CVE-YYYY-NNNN"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$",
            "description": "Semantic version number"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "ISO 8601 timestamp of when the entry was created"
        },
        "description": {
            "type": "string",
            "minLength": 1,
            "description": "Full description of the vulnerability"
        },
        "keyphrases": {
            "type": "object",
            "description": "Key phrases extracted from the vulnerability description",
            "required": [
                "rootcause",
                "weakness",
                "impact",
                "vector",
                "attacker",
                "product",
                "version",
                "component"
            ],
            "properties": {
                "rootcause": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The root cause(s) of the vulnerability"
                },
                "weakness": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The weakness(es) or vulnerability type(s)"
                },
                "impact": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The impact(s) of exploiting the vulnerability"
                },
                "vector": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The attack vector(s) or method(s) of exploitation"
                },
                "attacker": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "uniqueItems": true
                        }
                    ],
                    "description": "The type(s) of attacker who can exploit the vulnerability"
                },
                "product": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product name(s)"
                },
                "version": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The affected product version(s)"
                },
                "component": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "description": "The specific component(s) affected"
                }
            },
            "additionalProperties": false
        },
        "mitreTechnicalImpacts": {
            "type": "array",
            "description": "List of MITRE technical impact classifications",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        }
    },
    "additionalProperties": false
}

=== CyberSecAI/cve_info/2021/24xxx/CVE-2021-24000.json
{
    "cveId": "CVE-2021-24000",
    "version": "1.0.0",
    "timestamp": "2024-11-03T18:37:50.907685+00:00",
    "description": "A race condition with requestPointerLock() and setTimeout() could have resulted in a user interacting with one tab when they believed they were on a separate tab. In conjunction with certain elements (such as &ltinput type=file&gt) this could have led to an attack where a user was confused about the origin of the webpage and potentially disclosed information they did not intend to. This vulnerability affects Firefox < 88.",
    "keyphrases": {
        "rootcause": "race condition",
        "weakness": "",
        "impact": "disclose information",
        "vector": "",
        "attacker": "",
        "product": "Firefox",
        "version": "< 88",
        "component": ""
    },
    "mitreTechnicalImpacts": [
        "Read data"
    ]
}

=== CyberSecAI/cve_info/2017/14xxx/CVE-2017-14369.json
{
  "cveId": "CVE-2017-14369",
  "version": "1.0.0",
  "timestamp": "2024-12-11T16:08:24.783251+00:00",
  "description": "RSA Archer GRC Platform prior to 6.2.0.5 is affected by a privilege escalation vulnerability. A low privileged RSA Archer user may potentially exploit this vulnerability to elevate their privileges and export certain application records.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "privilege escalation vulnerability",
    "impact": "privilege escalation",
    "vector": "",
    "attacker": "low privileged RSA Archer user",
    "product": "RSA Archer GRC Platform",
    "version": "prior to 6.2.0.5",
    "component": ""
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2007/0xxx/CVE-2007-0133.json
{
  "cveId": "CVE-2007-0133",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "Multiple SQL injection vulnerabilities in display_review.php in iGeneric iG Shop 1.4 and earlier allow remote attackers to execute arbitrary SQL commands via the (1) id or (2) user_login_cookie parameter.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "SQL injection vulnerabilities",
    "impact": "execute arbitrary SQL commands",
    "vector": "",
    "attacker": "remote attackers",
    "product": "iGeneric iG Shop",
    "version": "1.4 and earlier",
    "component": "display_review.php"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2013/0xxx/CVE-2013-0754.json
{
  "cveId": "CVE-2013-0754",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "Use-after-free vulnerability in the ListenerManager implementation in Mozilla Firefox before 18.0, Firefox ESR 10.x before 10.0.12 and 17.x before 17.0.2, Thunderbird before 17.0.2, Thunderbird ESR 10.x before 10.0.12 and 17.x before 17.0.2, and SeaMonkey before 2.15 allows remote attackers to execute arbitrary code via vectors involving the triggering of garbage collection after memory allocation for listener objects.",
  "keyphrases": {
    "rootcause": "Use-after-free vulnerability",
    "weakness": "Use-after-free",
    "impact": "execute arbitrary code",
    "vector": "triggering of garbage collection after memory allocation for listener objects",
    "attacker": "remote attackers",
    "product": [
      "['Mozilla Firefox'",
      "'Firefox ESR'",
      "'Thunderbird'",
      "'Thunderbird ESR'",
      "'SeaMonkey']"
    ],
    "version": "various versions before specific releases",
    "component": "ListenerManager implementation"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2024/32xxx/CVE-2024-32167.json
{
  "cveId": "CVE-2024-32167",
  "version": "1.0.0",
  "timestamp": "2024-12-06T11:32:07.789868+00:00",
  "description": "Sourcecodester Online Medicine Ordering System 1.0 is vulnerable to Arbitrary file deletion vulnerability as the backend settings have the function of deleting pictures to delete any files.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "arbitrary file deletion",
    "impact": [
      "Arbitrary file deletion",
      "delete any files"
    ],
    "vector": "",
    "attacker": "",
    "product": "Sourcecodester Online Medicine Ordering System",
    "version": "1",
    "component": "backend settings"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2023/46xxx/CVE-2023-46814.json
{
  "cveId": "CVE-2023-46814",
  "version": "1.0.0",
  "timestamp": "2024-12-06T11:32:07.789868+00:00",
  "description": "A binary hijacking vulnerability exists within the VideoLAN VLC media player before 3.0.19 on Windows. The uninstaller attempts to execute code with elevated privileges out of a standard user writable location. Standard users may use this to gain arbitrary code execution as SYSTEM.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "binary hijacking",
    "impact": [
      "arbitrary code execution as SYSTEM",
      "execute code with elevated privileges"
    ],
    "vector": "",
    "attacker": "Standard users",
    "product": "VideoLAN VLC media player",
    "version": "before 3.0.19",
    "component": "uninstaller on Windows"
  },
  "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2022/21xxx/CVE-2022-21678.json
{
    "cveId": "CVE-2022-21678",
    "version": "1.0.0",
    "timestamp": "2024-11-03T18:37:50.907685+00:00",
    "description": "Discourse is an open source discussion platform. Prior to version 2.8.0.beta11 in the `tests-passed` branch, version 2.8.0.beta11 in the `beta` branch, and version 2.7.13 in the `stable` branch, the bios of users who made their profiles private were still visible in the `` tags on their users pages. The problem is patched in `tests-passed` version 2.8.0.beta11, `beta` version 2.8.0.beta11, and `stable` version 2.7.13 of Discourse.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "information disclosure",
        "impact": "",
        "vector": "",
        "attacker": "",
        "product": "Discourse",
        "version": "prior to 2.8.0.beta11 in tests-passed branch, 2.8.0.beta11 in beta branch, and 2.7.13 in stable branch",
        "component": ""
    },
    "mitreTechnicalImpacts": []
}

=== CyberSecAI/cve_info/2017/10xxx/CVE-2017-10615.json
{
  "cveId": "CVE-2017-10615",
  "version": "1.0.0",
  "timestamp": "2024-12-11T16:08:24.783251+00:00",
  "description": "A vulnerability in the pluggable authentication module (PAM) of Juniper Networks Junos OS may allow an unauthenticated network based attacker to potentially execute arbitrary code or crash daemons such as telnetd or sshd that make use of PAM. Affected Juniper Networks Junos OS releases are 14.1 from 14.1R5 prior to 14.1R8-S4, 14.1R9 14.1X53 prior to 14.1X53-D50 on EX and QFX series 14.2 from 14.2R3 prior to 14.2R7-S8, 14.2R8 No other Junos OS releases are affected by this issue. No other Juniper Networks products are affected by this issue.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "",
    "impact": [
      "crash daemons",
      "potentially execute arbitrary code"
    ],
    "vector": "",
    "attacker": "unauthenticated network based attacker",
    "product": "Juniper Networks Junos OS",
    "version": [
      "14.1 from 14.1R5 to 14.1R8-S4",
      "14.1R9 14.1X53 to 14.1X53-D50 on EX and QFX series",
      "14.2 from 14.2R3 to 14.2R7-S8",
      "14.2R8"
    ],
    "component": "pluggable authentication module (PAM)"
  },
  "mitreTechnicalImpacts": []
}
